source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'active_model_serializers'
gem 'pg'
gem 'devise'
gem 'versionist'
gem 'figaro'
gem 'font-awesome-rails'
gem 'simple_form'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'postgres_ext'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'unicorn'
gem 'chosen-rails', git: 'git://github.com/qpowell/chosen-rails.git'
gem 'acts_as_commentable'
gem 'acts_as_votable', '~> 0.10.0'
gem 'letter_opener', group: :development
gem 'ckeditor'
gem 'paperclip'
gem 'tagsinput-rails'
gem "nested_form"
gem 'kaminari'
gem 'sidekiq'
gem 'searchkick'
gem 'public_activity'
gem 'breadcrumbs_on_rails'
gem 'pushmeup'
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
gem 'ajax-datatables-rails'
gem 'smarter_csv'
gem 'mina-sidekiq'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
