# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad43a75d1a6ecddb38bdfdd92a52cc3066c5be962db6294e492de95c08a00b02878feabd02e8affb17b389bedb246aecbf02b1366b927d01490ec45dbbdffbe6

test:
  secret_key_base: b1c323aa44423e39828f867d5caceb627c367c251ae43967d463456a1a204155fae77bd07a932efdc3506b81aa7ba919e618edb34c564ea92ea520290f2d70c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:  Figaro.env.SECRET_KEY_BASE
