default: &default
  secret_key_base: 515a1c2fea6e4210200c28a235760ef99219341eef1a1b2a7cfe9ad2672390137119354a045209556f5688d8f45cc3c31e532f268fae0daeb827dd362c5c0f3d
  APNS_PORT: 2195
  APNS_PEM: <%= "#{Rails.root.to_s}/config/Push.pem" %>
  APNS_HOST: gateway.push.apple.com

development:
  <<: *default
  DP_LOCAL_USERNAME: shreya
  DP_LOCAL_PASSWORD: shreya


test:
  <<: *default
  DP_LOCAL_USERNAME: shreya
  DP_LOCAL_PASSWORD: shreya


production:
  <<: *default
  DP_DB_USERNAME: shreya
  DP_DB_PASSWORD: shreya
